package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Ban generated by hbm2java
 */
public class Ban implements java.io.Serializable {

	private int id;
	private Integer playerId;
	private Integer gameId;
	private Integer bannedFor;
	private Integer banPayed;

	public Ban() {
	}

	public Ban(int id) {
		this.id = id;
	}

	public Ban(int id, Integer playerId, Integer gameId, Integer bannedFor,
			Integer banPayed) {
		this.id = id;
		this.playerId = playerId;
		this.gameId = gameId;
		this.bannedFor = bannedFor;
		this.banPayed = banPayed;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	public Integer getBannedFor() {
		return this.bannedFor;
	}

	public void setBannedFor(Integer bannedFor) {
		this.bannedFor = bannedFor;
	}

	public Integer getBanPayed() {
		return this.banPayed;
	}

	public void setBanPayed(Integer banPayed) {
		this.banPayed = banPayed;
	}

}
