package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Finance generated by hbm2java
 */
public class Finance implements java.io.Serializable {

	private int id;
	private Integer teamId;
	private Integer seasonId;
	private Integer week;
	private Integer rectype;
	private Integer amount;

	public Finance() {
	}

	public Finance(int id) {
		this.id = id;
	}

	public Finance(int id, Integer teamId, Integer seasonId, Integer week,
			Integer rectype, Integer amount) {
		this.id = id;
		this.teamId = teamId;
		this.seasonId = seasonId;
		this.week = week;
		this.rectype = rectype;
		this.amount = amount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public Integer getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	public Integer getRectype() {
		return this.rectype;
	}

	public void setRectype(Integer rectype) {
		this.rectype = rectype;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
