package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

	private int id;
	private Team awayTeam;
	private Team homeTeam;
	private Integer seasonId;
	private Integer leagueId;
	private Integer week;
	private Integer score1;
	private Integer score2;
	private Integer attendance;
	private Integer percentAtt;
	private Date gameDate;
	private Set<GameDetail> gameDetails = new HashSet<GameDetail>(0);

	public Game() {
	}

	public Game(int id) {
		this.id = id;
	}

	public Game(Team homeTeam, Team awayTeam, Calendar cal, int seasonId, int leagueId, int week) {
		this(0, awayTeam, homeTeam, seasonId, leagueId, week, null, null, null, null, cal.getTime(), null);
	}
	public Game(int id, Team awayTeam, Team homeTeam, Integer seasonId, Integer leagueId,
			Integer week, Integer score1, Integer score2, Integer attendance,
			Integer percentAtt, Date gDate, Set<GameDetail> gameDetails) {
		this.id = id;
		this.awayTeam = awayTeam;
		this.homeTeam = homeTeam;
		this.seasonId = seasonId;
		this.leagueId = leagueId;
		this.week = week;
		this.score1 = score1;
		this.score2 = score2;
		this.attendance = attendance;
		this.percentAtt = percentAtt;
		this.gameDate = gDate;
		this.gameDetails = gameDetails;
	}

	public Game(Game game) {
		this.id = game.getId();
		this.awayTeam = game.getAwayTeam();
		this.homeTeam = game.getHomeTeam();
		this.seasonId = game.getSeasonId();
		this.week = game.getWeek();
		this.score1 = game.getScore1();
		this.score2 = game.getScore2();
		this.attendance = game.getAttendance();
		this.percentAtt = game.getPercentAtt();
		this.gameDate = game.getGameDate();
		this.gameDetails = game.getGameDetails();
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Team getAwayTeam() {
		return this.awayTeam;
	}

	public void setAwayTeam(Team awayTeam) {
		this.awayTeam = awayTeam;
	}

	public Team getHomeTeam() {
		return this.homeTeam;
	}

	public void setHomeTeam(Team homeTeam) {
		this.homeTeam = homeTeam;
	}

	public Integer getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	public Integer getScore1() {
		return this.score1;
	}

	public void setScore1(Integer score1) {
		this.score1 = score1;
	}

	public Integer getScore2() {
		return this.score2;
	}

	public void setScore2(Integer score2) {
		this.score2 = score2;
	}

	public Integer getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Integer attendance) {
		this.attendance = attendance;
	}

	public Integer getPercentAtt() {
		return this.percentAtt;
	}

	public void setPercentAtt(Integer percentAtt) {
		this.percentAtt = percentAtt;
	}

	public Set<GameDetail> getGameDetails() {
		return this.gameDetails;
	}

	public void setGameDetails(Set<GameDetail> gameDetails) {
		this.gameDetails = gameDetails;
	}

	public Date getGameDate() {
		return gameDate;
	}

	public void setGameDate(Date gameDate) {
		this.gameDate = gameDate;
	}

	public Integer getLeagueId() {
		return leagueId;
	}

	public void setLeagueId(Integer leagueId) {
		this.leagueId = leagueId;
	}

}
