package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Injury generated by hbm2java
 */
public class Injury implements java.io.Serializable {

	private int id;
	private Integer playerId;
	private Integer gameId;
	private Integer injuredFor;
	private Integer injuredPayed;

	public Injury() {
	}

	public Injury(int id) {
		this.id = id;
	}

	public Injury(int id, Integer playerId, Integer gameId, Integer injuredFor,
			Integer injuredPayed) {
		this.id = id;
		this.playerId = playerId;
		this.gameId = gameId;
		this.injuredFor = injuredFor;
		this.injuredPayed = injuredPayed;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	public Integer getInjuredFor() {
		return this.injuredFor;
	}

	public void setInjuredFor(Integer injuredFor) {
		this.injuredFor = injuredFor;
	}

	public Integer getInjuredPayed() {
		return this.injuredPayed;
	}

	public void setInjuredPayed(Integer injuredPayed) {
		this.injuredPayed = injuredPayed;
	}

}
