package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * LeagueTeam generated by hbm2java
 */
public class LeagueTeam implements java.io.Serializable {

	private int id;
	private Integer leagueId;
	private Integer teamId;
	private Integer seasonId;
	private Integer played;
	private Integer won;
	private Integer lost;
	private Integer draw;
	private Integer forGoal;
	private Integer againstGoal;
	private Integer points;

	public LeagueTeam() {
	}

	public LeagueTeam(int id) {
		this.id = id;
	}

	public LeagueTeam(int id, Integer leagueId, Integer teamId,
			Integer seasonId, Integer played, Integer won, Integer lost,
			Integer draw, Integer forGoal, Integer againstGol, Integer points) {
		this.id = id;
		this.leagueId = leagueId;
		this.teamId = teamId;
		this.seasonId = seasonId;
		this.played = played;
		this.won = won;
		this.lost = lost;
		this.draw = draw;
		this.forGoal = forGoal;
		this.againstGoal = againstGol;
		this.points = points;
	}

	public LeagueTeam(int _leagueId, int _teamId, int _seasonId) {
		this(0, _leagueId, _teamId, _seasonId, 0, 0, 0,0,0,0,0);
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getLeagueId() {
		return this.leagueId;
	}

	public void setLeagueId(Integer leagueId) {
		this.leagueId = leagueId;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public Integer getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getPlayed() {
		return this.played;
	}

	public void setPlayed(Integer played) {
		this.played = played;
	}

	public Integer getWon() {
		return this.won;
	}

	public void setWon(Integer won) {
		this.won = won;
	}

	public Integer getLost() {
		return this.lost;
	}

	public void setLost(Integer lost) {
		this.lost = lost;
	}

	public Integer getDraw() {
		return this.draw;
	}

	public void setDraw(Integer draw) {
		this.draw = draw;
	}

	public Integer getForGoal() {
		return this.forGoal;
	}

	public void setForGoal(Integer forGoal) {
		this.forGoal = forGoal;
	}


	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

	public Integer getAgainstGoal() {
		return againstGoal;
	}

	public void setAgainstGoal(Integer againstGoal) {
		this.againstGoal = againstGoal;
	}

}
