package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * League generated by hbm2java
 */
public class League implements java.io.Serializable {
	
	public static final int STATUS_NEWSEASON		= 0;
	public static final int STATUS_STARTED			= 1;
	public static final int STATUS_COMPLETED		= 2;
	
	private int id;
	private League parent;
	private String name;
	private Integer level;
	private Integer size;
	private Integer relegations;
	private Integer promotions;
	private Integer playoffs;
	private Integer status;

	public League() {
	}

	public League(int id) {
		this.id = id;
	}

	public League(int id, League parent, String name, Integer level,
			Integer size, Integer relegations, Integer promotions,
			Integer playoffs) {
		this.id = id;
		this.parent = parent;
		this.name = name;
		this.level = level;
		this.size = size;
		this.relegations = relegations;
		this.promotions = promotions;
		this.playoffs = playoffs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public League getParent() {
		return this.parent;
	}

	public void setParent(League parent) {
		this.parent = parent;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public Integer getRelegations() {
		return this.relegations;
	}

	public void setRelegations(Integer relegations) {
		this.relegations = relegations;
	}

	public Integer getPromotions() {
		return this.promotions;
	}

	public void setPromotions(Integer promotions) {
		this.promotions = promotions;
	}

	public Integer getPlayoffs() {
		return this.playoffs;
	}

	public void setPlayoffs(Integer playoffs) {
		this.playoffs = playoffs;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
