package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private int id;
	private String firstname;
	private String lastname;
	private transient String teamName;
	private String nationality;
	private String language;
	private String device;
	private String deviceId;
	private Date birthdate;
	private Date registerDate;
	private Integer currentTeam;

	public Manager() {
	}

	public Manager(int id) {
		this.id = id;
	}

	public Manager(int id, String firstname, String lastname,
			String nationality, String language, Date birthdate,
			Date registerDate, Integer currentTeam) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.nationality = nationality;
		this.language = language;
		this.birthdate = birthdate;
		this.registerDate = registerDate;
		this.currentTeam = currentTeam;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public Integer getCurrentTeam() {
		return this.currentTeam;
	}

	public void setCurrentTeam(Integer currentTeam) {
		this.currentTeam = currentTeam;
	}

	public String getDevice() {
		return device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getTeamName() {
		return teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

}
