package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * ModifyCount generated by hbm2java
 */
public class ModifyCount implements java.io.Serializable {

	private int id;
	private Integer managerId;
	private Integer teamId;
	private Integer leagueId;
	private Integer seasonId;
	private Integer maxNews;
	private Integer maxGames;
	private Integer maxFinance;

	public ModifyCount() {
	}

	public ModifyCount(int id) {
		this.id = id;
	}
	public ModifyCount(ModifyCount mc) {
		id = mc.getId();
		managerId = mc.getManagerId();
		teamId = mc.getTeamId();
		leagueId = mc.getLeagueId();
		seasonId = mc.getSeasonId();
		maxNews = mc.getMaxNews();
		maxGames = mc.getMaxGames();
		maxFinance = mc.getMaxFinance();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getManagerId() {
		return managerId;
	}

	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	public Integer getTeamId() {
		return teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public Integer getLeagueId() {
		return leagueId;
	}

	public void setLeagueId(Integer leagueId) {
		this.leagueId = leagueId;
	}

	public Integer getSeasonId() {
		return seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getMaxNews() {
		return maxNews;
	}

	public void setMaxNews(Integer maxNews) {
		this.maxNews = maxNews;
	}

	public Integer getMaxGames() {
		return maxGames;
	}

	public void setMaxGames(Integer maxGames) {
		this.maxGames = maxGames;
	}

	public Integer getMaxFinance() {
		return maxFinance;
	}

	public void setMaxFinance(Integer maxFinance) {
		this.maxFinance = maxFinance;
	}


}
