package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private int id;
	private int managerId;
	private Date receiveDate;
	private String subject;
	private Integer mustAnswer;
	private String body;

	public News() {
	}

	public News(int id, int managerId) {
		this.id = id;
		this.managerId = managerId;
	}

	public News(int id, int managerId, Date receiveDate, String subject,
			Integer mustAnswer, String body) {
		this.id = id;
		this.managerId = managerId;
		this.receiveDate = receiveDate;
		this.subject = subject;
		this.mustAnswer = mustAnswer;
		this.body = body;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getManagerId() {
		return this.managerId;
	}

	public void setManagerId(int managerId) {
		this.managerId = managerId;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Integer getMustAnswer() {
		return this.mustAnswer;
	}

	public void setMustAnswer(Integer mustAnswer) {
		this.mustAnswer = mustAnswer;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

}
