package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerPerformance generated by hbm2java
 */
public class PlayerPerformance implements java.io.Serializable {

	private int id;
	private Player player;
	private String  position;
	private Integer gameId;
	private Integer teamId;
	private Integer seasonId;
	private Integer mins;
	private Integer assist;
	private Integer goal;
	private Integer form;
	private Integer morale;
	private transient int played;

	public PlayerPerformance() {
	}
	
	public PlayerPerformance(PlayerPerformance pp) {
		this.id = pp.getId();
		this.player = pp.getPlayer();
		this.position = pp.getPosition();
		this.gameId = pp.getGameId();
		this.teamId = pp.getTeamId();
		this.seasonId = pp.getSeasonId();
		this.mins = pp.getMins();
		this.assist = pp.getAssist();
		this.goal = pp.getGoal();
		this.form = pp.getForm();
		this.morale = pp.getMorale();
	}

	public PlayerPerformance(int id) {
		this.id = id;
	}

	public PlayerPerformance(int id, Player player, Integer gameId,
			Integer mins, Integer assist, Integer goal, Integer form) {
		this.id = id;
		this.player = player;
		this.gameId = gameId;
		this.mins = mins;
		this.assist = assist;
		this.goal = goal;
		this.form = form;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player playerId) {
		this.player = playerId;
	}

	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	public Integer getMins() {
		return this.mins;
	}

	public void setMins(Integer mins) {
		this.mins = mins;
	}

	public Integer getAssist() {
		return this.assist;
	}

	public void setAssist(Integer assist) {
		this.assist = assist;
	}

	public Integer getGoal() {
		return this.goal;
	}

	public void setGoal(Integer goal) {
		this.goal = goal;
	}

	public Integer getForm() {
		return this.form;
	}

	public void setForm(Integer form) {
		this.form = form;
	}

	public Integer getSeasonId() {
		return seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getMorale() {
		return morale;
	}

	public void setMorale(Integer morale) {
		this.morale = morale;
	}
	
	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Integer getTeamId() {
		return teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public int getPlayed() {
		return played;
	}

	public void setPlayed(int played) {
		this.played = played;
	}
}
