package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerPerformance generated by hbm2java
 */
public class PlayerPerformance implements java.io.Serializable {

	private int id;
	private Integer playerId;
	private Integer gameId;
	private Integer seasonId;
	private Integer mins;
	private Integer assist;
	private Integer goal;
	private Integer form;
	private Integer morale;

	public PlayerPerformance() {
	}

	public PlayerPerformance(int id) {
		this.id = id;
	}

	public PlayerPerformance(int id, Integer playerId, Integer gameId,
			Integer mins, Integer assist, Integer goal, Integer form) {
		this.id = id;
		this.playerId = playerId;
		this.gameId = gameId;
		this.mins = mins;
		this.assist = assist;
		this.goal = goal;
		this.form = form;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	public Integer getMins() {
		return this.mins;
	}

	public void setMins(Integer mins) {
		this.mins = mins;
	}

	public Integer getAssist() {
		return this.assist;
	}

	public void setAssist(Integer assist) {
		this.assist = assist;
	}

	public Integer getGoal() {
		return this.goal;
	}

	public void setGoal(Integer goal) {
		this.goal = goal;
	}

	public Integer getForm() {
		return this.form;
	}

	public void setForm(Integer form) {
		this.form = form;
	}

	public Integer getSeasonId() {
		return seasonId;
	}

	public void setSeasonId(Integer seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getMorale() {
		return morale;
	}

	public void setMorale(Integer morale) {
		this.morale = morale;
	}

}
