package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerSkill generated by hbm2java
 */
public class PlayerSkill implements java.io.Serializable {

	private int id;
	private Player player;
	private Integer handling;
	private Integer tackling;
	private Integer passing;
	private Integer creativity;
	private Integer positioning;
	private Integer teamwork;
	private Integer heading;
	private Integer shooting;
	private Integer dribbling;
	private Integer reflexes;
	private Integer finishing;
	private Integer crossing;
	private Integer technique;
	private Integer firstTouch;
	private Integer composure;
	private Integer agility;
	private Integer acceleration;
	private Integer stamina;
	private Integer strength;

	public PlayerSkill() {
	}

	public PlayerSkill(Player player) {
		this.player = player;
	}

	public PlayerSkill(Player player, Integer handling, Integer tackling,
			Integer passing, Integer creativity, Integer positioning,
			Integer teamwork, Integer heading, Integer shooting,
			Integer dribbling, Integer reflexes, Integer finishing,
			Integer crossing, Integer technique, Integer firstTouch,
			Integer composure, Integer agility, Integer acceleration,
			Integer stamina, Integer strength) {
		this.player = player;
		this.handling = handling;
		this.tackling = tackling;
		this.passing = passing;
		this.creativity = creativity;
		this.positioning = positioning;
		this.teamwork = teamwork;
		this.heading = heading;
		this.shooting = shooting;
		this.dribbling = dribbling;
		this.reflexes = reflexes;
		this.finishing = finishing;
		this.crossing = crossing;
		this.technique = technique;
		this.firstTouch = firstTouch;
		this.composure = composure;
		this.agility = agility;
		this.acceleration = acceleration;
		this.stamina = stamina;
		this.strength = strength;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Integer getHandling() {
		return this.handling;
	}

	public void setHandling(Integer handling) {
		this.handling = handling;
	}

	public Integer getTackling() {
		return this.tackling;
	}

	public void setTackling(Integer tackling) {
		this.tackling = tackling;
	}

	public Integer getPassing() {
		return this.passing;
	}

	public void setPassing(Integer passing) {
		this.passing = passing;
	}

	public Integer getCreativity() {
		return this.creativity;
	}

	public void setCreativity(Integer creativity) {
		this.creativity = creativity;
	}

	public Integer getPositioning() {
		return this.positioning;
	}

	public void setPositioning(Integer positioning) {
		this.positioning = positioning;
	}

	public Integer getTeamwork() {
		return this.teamwork;
	}

	public void setTeamwork(Integer teamwork) {
		this.teamwork = teamwork;
	}

	public Integer getHeading() {
		return this.heading;
	}

	public void setHeading(Integer heading) {
		this.heading = heading;
	}

	public Integer getShooting() {
		return this.shooting;
	}

	public void setShooting(Integer shooting) {
		this.shooting = shooting;
	}

	public Integer getDribbling() {
		return this.dribbling;
	}

	public void setDribbling(Integer dribbling) {
		this.dribbling = dribbling;
	}

	public Integer getReflexes() {
		return this.reflexes;
	}

	public void setReflexes(Integer reflexes) {
		this.reflexes = reflexes;
	}

	public Integer getFinishing() {
		return this.finishing;
	}

	public void setFinishing(Integer finishing) {
		this.finishing = finishing;
	}

	public Integer getCrossing() {
		return this.crossing;
	}

	public void setCrossing(Integer crossing) {
		this.crossing = crossing;
	}

	public Integer getTechnique() {
		return this.technique;
	}

	public void setTechnique(Integer technique) {
		this.technique = technique;
	}

	public Integer getFirstTouch() {
		return this.firstTouch;
	}

	public void setFirstTouch(Integer firstTouch) {
		this.firstTouch = firstTouch;
	}

	public Integer getComposure() {
		return this.composure;
	}

	public void setComposure(Integer composure) {
		this.composure = composure;
	}

	public Integer getAgility() {
		return this.agility;
	}

	public void setAgility(Integer agility) {
		this.agility = agility;
	}

	public Integer getAcceleration() {
		return this.acceleration;
	}

	public void setAcceleration(Integer acceleration) {
		this.acceleration = acceleration;
	}

	public Integer getStamina() {
		return this.stamina;
	}

	public void setStamina(Integer stamina) {
		this.stamina = stamina;
	}

	public Integer getStrength() {
		return this.strength;
	}

	public void setStrength(Integer strength) {
		this.strength = strength;
	}

}
