package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Player generated by hbm2java
 */
public class Player implements java.io.Serializable {

	@Override
	public String toString() {
		return ""+getId();
	}
	private int id;
	private String name;
	private String surname;
	private String position;
	private Date birthdate;
	private Integer currentTeam;
	private Integer fitness;
	private Integer morale;
	private Integer quality;
	private String  latestForm;
	private PlayerSkill playerSkill;
	private transient Team teamObj;

	public Player() {
	}
	public Player(Player p) {
		this.id = p.getId();
		this.name = p.getName();
		this.surname = p.getSurname();
		this.position = p.getPosition();
		this.birthdate = p.getBirthdate();
		this.currentTeam = p.getCurrentTeam();
		this.fitness = p.getFitness();
		this.morale = p.getMorale();
		this.latestForm = p.getLatestForm(); 
		this.quality = p.getQuality();
		this.playerSkill = p.getPlayerSkill();
		this.teamObj = p.getTeamObj();
	}

	public Player(int id) {
		this.id = id;
	}

	public Player(int id, String name, String position, Date birthdate,
			Integer currentTeam, Integer fitness, Integer morale,
			Integer quality, PlayerSkill playerSkill) {
		this.id = id;
		this.name = name;
		this.position = position;
		this.birthdate = birthdate;
		this.currentTeam = currentTeam;
		this.fitness = fitness;
		this.morale = morale;
		this.quality = quality;
		this.playerSkill = playerSkill;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public Integer getCurrentTeam() {
		return this.currentTeam;
	}

	public void setCurrentTeam(Integer currentTeam) {
		this.currentTeam = currentTeam;
	}

	public Integer getFitness() {
		return this.fitness;
	}

	public void setFitness(Integer fitnss) {
		if (fitnss > 100)
			fitnss = 100;
		this.fitness = fitnss;
	}

	public Integer getMorale() {
		return this.morale;
	}

	public void setMorale(Integer morale) {
		this.morale = morale;
	}

	public Integer getQuality() {
		return this.quality;
	}

	public void setQuality(Integer quality) {
		this.quality = quality;
	}

	public PlayerSkill getPlayerSkill() {
		return this.playerSkill;
	}

	public void setPlayerSkill(PlayerSkill playerSkill) {
		this.playerSkill = playerSkill;
	}

	public String getFormattedLatestForm() {
		if (latestForm == null || latestForm.trim().length() == 0)
			return "-";
		String[] vals = latestForm.split("/");
		StringBuffer buffer = new StringBuffer();
		for (int i = 0; i < vals.length; i++) {
			if (i > 0)
				buffer.append("/");
			float val =  Float.parseFloat(vals[i]) / 100;
			buffer.append(String.format("%(.0f", val));
		}
		return buffer.toString();
	}
	public String getLatestForm() {
		return latestForm;
	}

	public void setLatestForm(String latestForm) {
		this.latestForm = latestForm;
	}

	public String getSurname() {
		return surname;
	}
	public String getShortName() {
		String shortName = "";
		if (name != null && name.trim().length()>0)
			shortName = name.trim().charAt(0) + ".";
		if (surname!=null)
			shortName = shortName + surname;
		else
			shortName = name;
		return shortName;
	}
	public String getFullName() {
		String fullName = "";
		if (name != null && name.trim().length()>0)
			fullName = name.trim() + " ";
		if (surname!=null)
			fullName = fullName + surname;
		else
			fullName = name;
		return fullName;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}
	public Team getTeamObj() {
		return teamObj;
	}
	public void setTeamObj(Team team) {
		this.teamObj = team;
	}

}
