package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerTemplate generated by hbm2java
 */
public class PlayerTemplate implements java.io.Serializable {

	private int id;
	private String country;
	private String name;
	private String surname;

	public PlayerTemplate() {
	}

	public PlayerTemplate(int id) {
		this.id = id;
	}

	public PlayerTemplate(int id, String country, String name, String surname) {
		this.id = id;
		this.country = country;
		this.name = name;
		this.surname = surname;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
