package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Player generated by hbm2java
 */
public class Player implements java.io.Serializable {

	@Override
	public String toString() {
		return ""+getId();
	}
	private int id;
	private String name;
	private String surname;
	private String position;
	private Date birthdate;
	private Integer currentTeam;
	private Integer fitness;
	private Integer morale;
	private Integer quality;
	private String  latestForm;
	private PlayerSkill playerSkill;

	public Player() {
	}

	public Player(int id) {
		this.id = id;
	}

	public Player(int id, String name, String position, Date birthdate,
			Integer currentTeam, Integer fitness, Integer morale,
			Integer quality, PlayerSkill playerSkill) {
		this.id = id;
		this.name = name;
		this.position = position;
		this.birthdate = birthdate;
		this.currentTeam = currentTeam;
		this.fitness = fitness;
		this.morale = morale;
		this.quality = quality;
		this.playerSkill = playerSkill;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public Integer getCurrentTeam() {
		return this.currentTeam;
	}

	public void setCurrentTeam(Integer currentTeam) {
		this.currentTeam = currentTeam;
	}

	public Integer getFitness() {
		return this.fitness;
	}

	public void setFitness(Integer fitnss) {
		if (fitnss > 100)
			fitnss = 100;
		this.fitness = fitnss;
	}

	public Integer getMorale() {
		return this.morale;
	}

	public void setMorale(Integer morale) {
		this.morale = morale;
	}

	public Integer getQuality() {
		return this.quality;
	}

	public void setQuality(Integer quality) {
		this.quality = quality;
	}

	public PlayerSkill getPlayerSkill() {
		return this.playerSkill;
	}

	public void setPlayerSkill(PlayerSkill playerSkill) {
		this.playerSkill = playerSkill;
	}

	public String getLatestForm() {
		return latestForm;
	}

	public void setLatestForm(String latestForm) {
		this.latestForm = latestForm;
	}

	public String getSurname() {
		return surname;
	}
	public String getShortName() {
		String shortName = "";
		if (name != null && name.trim().length()>0)
			shortName = name.trim().charAt(0) + ".";
		if (surname!=null)
			shortName = shortName + surname;
		else
			shortName = name;
		return shortName;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
