package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Stadium generated by hbm2java
 */
public class Stadium implements java.io.Serializable {

	private int id;
	private String name;
	private Integer capacity;
	private Set<Team> teams = new HashSet<Team>(0);

	public Stadium() {
	}

	public Stadium(int id) {
		this.id = id;
	}

	public Stadium(int id, String name, Integer capacity, Set<Team> teams) {
		this.id = id;
		this.name = name;
		this.capacity = capacity;
		this.teams = teams;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

}
