package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * TacticPlayer generated by hbm2java
 */
public class TacticPlayer implements java.io.Serializable {

	private int id;
	private Integer tacticId;
	private Integer playerId;
	private String position;
	private transient Player player;
	
	public TacticPlayer() {
	}

	public TacticPlayer(int id) {
		this.id = id;
	}

	public TacticPlayer(int id, Integer tacticId, Integer playerId,
			String position) {
		this.id = id;
		this.tacticId = tacticId;
		this.playerId = playerId;
		this.position = position;
	}
	public TacticPlayer(TacticPlayer tp) {
		this.id = tp.getId();
		this.tacticId = tp.getTacticId();
		this.playerId = tp.getPlayerId();
		this.position = tp.getPosition();
		this.player = tp.getPlayer();
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getTacticId() {
		return this.tacticId;
	}

	public void setTacticId(Integer tacticId) {
		this.tacticId = tacticId;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Player getPlayer() {
		return player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

}
