package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * TeamManager generated by hbm2java
 */
public class TeamManager implements java.io.Serializable {

	private int id;
	private int managerId;
	private int teamId;
	private int seasonId;
	private Integer played;
	private Integer win;
	private Integer draw;
	private Integer loss;

	public TeamManager() {
	}

	public TeamManager(int managerId, int teamId, int seasonId) {
		this(0, managerId, teamId, seasonId, 0, 0, 0, 0);
	}

	public TeamManager(int id, int managerId, int teamId, int seasonId,
			Integer played, Integer win, Integer draw, Integer loss) {
		this.id = id;
		this.managerId = managerId;
		this.teamId = teamId;
		this.seasonId = seasonId;
		this.played = played;
		this.win = win;
		this.draw = draw;
		this.loss = loss;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getManagerId() {
		return this.managerId;
	}

	public void setManagerId(int managerId) {
		this.managerId = managerId;
	}

	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	public int getSeasonId() {
		return this.seasonId;
	}

	public void setSeasonId(int seasonId) {
		this.seasonId = seasonId;
	}

	public Integer getPlayed() {
		return this.played;
	}

	public void setPlayed(Integer played) {
		this.played = played;
	}

	public Integer getWin() {
		return this.win;
	}

	public void setWin(Integer win) {
		this.win = win;
	}

	public Integer getDraw() {
		return this.draw;
	}

	public void setDraw(Integer draw) {
		this.draw = draw;
	}

	public Integer getLoss() {
		return this.loss;
	}

	public void setLoss(Integer loss) {
		this.loss = loss;
	}

}
