package com.fm.dal;

// Generated Nov 24, 2011 11:03:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * TeamTemplate generated by hbm2java
 */
public class TeamTemplate implements java.io.Serializable {

	private int id;
	private String team;
	private String country;
	private String color1;
	private String color2;
	private Integer used;

	public TeamTemplate() {
	}

	public TeamTemplate(int id) {
		this.id = id;
	}

	public TeamTemplate(int id, String team, String country, String color1,
			String color2) {
		this.id = id;
		this.team = team;
		this.country = country;
		this.color1 = color1;
		this.color2 = color2;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	public String getColor1() {
		return this.color1;
	}

	public void setColor1(String color1) {
		this.color1 = color1;
	}

	public String getColor2() {
		return this.color2;
	}

	public void setColor2(String color2) {
		this.color2 = color2;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getUsed() {
		return used;
	}

	public void setUsed(Integer used) {
		this.used = used;
	}

}
