
DROP TABLE IF EXISTS "NEWS_BODY";
DROP TABLE IF EXISTS "TACTIC_PLAYER";
DROP TABLE IF EXISTS "CURRENT";
DROP TABLE IF EXISTS "NEWS";
DROP TABLE IF EXISTS "PLAYER";
DROP TABLE IF EXISTS "TACTIC";
DROP TABLE IF EXISTS "TEAM";
DROP TABLE IF EXISTS "FIXTURE";
DROP TABLE IF EXISTS "LEAGUE_TABLE";
DROP TABLE IF EXISTS "FINANCE";

CREATE TABLE "FINANCE" (
       "ID" INTEGER NOT NULL
     , "TEAM_ID" INTEGER
     , "SEASON_ID" INTEGER
     , "WEEK" INTEGER
     , "RECTYPE" INTEGER
     , "AMOUNT" INTEGER
     , CONSTRAINT "PK_FINANCE" PRIMARY KEY ("ID")
);

CREATE TABLE "LEAGUE_TABLE" (
       "ID" INTEGER NOT NULL CONSTRAINT "PK_LEAGUE_TABLE" PRIMARY KEY AUTOINCREMENT
     , "TEAM_ID" INTEGER
     , "PLAYED" INTEGER DEFAULT 0
     , "WON" INTEGER DEFAULT 0
     , "LOST" INTEGER DEFAULT 0
     , "DRAW" INTEGER DEFAULT 0
     , "FOR_GOAL" INTEGER DEFAULT 0
     , "AGAINST_GOAL" INTEGER DEFAULT 0
     , "POINTS" INTEGER DEFAULT 0
);

CREATE TABLE "FIXTURE" (
       "ID" INTEGER NOT NULL
     , "TEAM1" INTEGER
     , "TEAM2" INTEGER
     , "SEASON_ID" INTEGER
     , "WEEK" INTEGER
     , "SCORE1" INTEGER
     , "SCORE2" INTEGER
     , "ATTENDANCE" INTEGER
     , "GAME_DATE" VARCHAR(16)
     , CONSTRAINT "PK_FIXTURE" PRIMARY KEY ("ID")
);

CREATE TABLE "TEAM" (
       "ID" INTEGER NOT NULL
     , "NAME" VARCHAR(64) NOT NULL
     , "COLOR1" VARCHAR(16)
     , "COLOR2" VARCHAR(16)
     , "CURRENT_LEAGUE" INTEGER DEFAULT 0
     , "MANAGER" VARCHAR(128)
     , "STADIUM" VARCHAR(128)
     , CONSTRAINT "PK_TEAM" PRIMARY KEY ("ID")
);

CREATE TABLE "TACTIC" (
       "ID" INTEGER NOT NULL
     , "TEAM_ID" INTEGER
     , "FORMATION" INTEGER
     , CONSTRAINT "PK_TACTIC" PRIMARY KEY ("ID")
);

CREATE TABLE "PLAYER" (
       "ID" INTEGER NOT NULL
     , "NAME" VARCHAR(64)
     , "POSITION" VARCHAR(16)
     , "BIRTHDATE" VARCHAR(8)
     , "CURRENT_TEAM" INTEGER DEFAULT 0
     , "FITNESS" INTEGER
     , "MORALE" INTEGER
     , "QUALITY" INTEGER
     , CONSTRAINT "PK_PLAYER" PRIMARY KEY ("ID")
);

CREATE TABLE "NEWS" (
       "ID" INTEGER NOT NULL
     , "MANAGER_ID" INTEGER NOT NULL
     , "RECEIVE_DATE" VARCHAR(16)
     , "SUBJECT" VARCHAR(128)
     , "MUST_ANSWER" INTEGER
     , "READ" INTEGER
     , CONSTRAINT "PK_NEWS" PRIMARY KEY ("ID")
);

CREATE TABLE "CURRENT" (
       "MANAGER_ID" INTEGER NOT NULL
     , "TEAM_ID" INTEGER
     , "LEAGUE_ID" INTEGER
     , "SEASON_ID" INTEGER
     , "MAX_GAMES" INTEGER
     , "MAX_NEWS" INTEGER
     , "MAX_FINANCE" INTEGER
     , CONSTRAINT "PK_CURRENT" PRIMARY KEY ("MANAGER_ID")
);

CREATE TABLE "TACTIC_PLAYER" (
       "ID" INTEGER NOT NULL
     , "TACTIC_ID" INTEGER
     , "PLAYER_ID" INTEGER
     , "POSITION" VARCHAR(16)
     , CONSTRAINT "PK_TACTIC_PLAYER" PRIMARY KEY ("ID")
     , CONSTRAINT "FK_TACTIC_PLAYER_1" FOREIGN KEY ("PLAYER_ID")
                  REFERENCES "PLAYER" ("ID")
     , CONSTRAINT "FK_TACTIC_PLAYER_2" FOREIGN KEY ("TACTIC_ID")
                  REFERENCES "TACTIC" ("ID")
);

CREATE TABLE "NEWS_BODY" (
       "ID" INTEGER NOT NULL
     , "BODY" TEXT
     , CONSTRAINT "PK_NEWS_BODY" PRIMARY KEY ("ID")
     , CONSTRAINT "FK_NEWS_BODY_1" FOREIGN KEY ("ID")
                  REFERENCES "NEWS" ("ID")
);

