CREATE TRIGGER TEAM_INS_TRG INSERT ON TEAM 
 BEGIN
  INSERT INTO LEAGUE_TABLE (TEAM_ID) VALUES (NEW.ID);
 END;
 
CREATE TRIGGER NEWBODY_INS_TRG INSERT ON NEWS_BODY 
 BEGIN
  UPDATE NEWS SET READ = 1 WHERE ID = NEW.ID;
 END;

 CREATE TRIGGER NEWS_INS_TRG INSERT ON NEWS 
 BEGIN
  UPDATE CURRENT SET MAX_NEWS = NEW.ID;
 END;
 
 CREATE TRIGGER FINANCE_INS_TRG INSERT ON FINANCE 
 BEGIN
  UPDATE CURRENT SET MAX_FINANCE = NEW.ID;
 END;
 
 CREATE TRIGGER FIXURE_UPD_TRG UPDATE OF SCORE1 ON FIXTURE
 BEGIN
  UPDATE CURRENT SET MAX_GAMES = NEW.ID;
   IF NEW.SCORE1 > NEW.SCORE2 THEN
    update LEAGUE_TABLE set WON = WON + 1, PLAYER = PLAYED + 1, FOR_GOAL = FOR_GOAL + NEW.SCORE1, AGAINST_GOAL = AGAINST_GOAL + NEW.SCORE2, POINT = POINT + 3 where TEAM_ID = NEW.TEAM1;
    update LEAGUE_TABLE set LOST = LOST + 1, PLAYER = PLAYED + 1, FOR_GOAL = FOR_GOAL + NEW.SCORE2, AGAINST_GOAL = AGAINST_GOAL + NEW.SCORE1 where TEAM_ID = NEW.TEAM2;
   END IF;
   IF NEW.SCORE1 = NEW.SCORE2 THEN
    update LEAGUE_TABLE set DRAW = DRAW + 1, PLAYER = PLAYED + 1, FOR_GOAL = FOR_GOAL + NEW.SCORE1, AGAINST_GOAL = AGAINST_GOAL + NEW.SCORE2, POINT = POINT + 1 where TEAM_ID = NEW.TEAM1;
    update LEAGUE_TABLE set DRAW = DRAW + 1, PLAYER = PLAYED + 1, FOR_GOAL = FOR_GOAL + NEW.SCORE2, AGAINST_GOAL = AGAINST_GOAL + NEW.SCORE1, POINT = POINT + 1 where TEAM_ID = NEW.TEAM2;
  END IF;
  IF NEW.SCORE1 < NEW.SCORE2 THEN
    update LEAGUE_TABLE set WON = WON + 1, PLAYER = PLAYED + 1, FOR_GOAL = FOR_GOAL + NEW.SCORE2, AGAINST_GOAL = AGAINST_GOAL + NEW.SCORE1, POINT = POINT + 3 where TEAM_ID = NEW.TEAM2;
    update LEAGUE_TABLE set LOST = LOST + 1, PLAYER = PLAYED + 1, FOR_GOAL = FOR_GOAL + NEW.SCORE1, AGAINST_GOAL = AGAINST_GOAL + NEW.SCORE2	where TEAM_ID = NEW.TEAM1;
  END IF;
 END;
 