insert into TEAM_TEMPLATE values (1, 'Fenerbahce', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (2, 'Ankaragucu', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (3, 'CimbomGucu', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (4, 'YenerBahce', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (5, 'Sekiztas', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (6, 'Bursaspor', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (7, 'Sakarbahce', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (8, 'Sekerspor', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (9, 'Trabzon', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (10, 'Hamsigucu', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (11, 'PlazmaSpor', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (12, 'Enayispor', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (13, 'DefansGucu fc', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (14, 'Galatasaray', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (15, 'Besiktas', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (16, 'Diyarkabar', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (17, 'Kasimpasa', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (18, 'IBB', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (19, 'VTGucu', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (20, 'Avea Spor', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (21, 'TRCell', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (22, 'Onur', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (23, 'Oral', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (24, 'Ali', 'turkey', 'Yellow', 'Blue', NULL);
insert into TEAM_TEMPLATE values (25, 'Bulent', 'turkey', 'Yellow', 'Blue', NULL);
